name: oubliette
description: "Cross-platform secure storage for Flutter (Android Keystore, iOS/macOS Keychain)."
version: 0.0.1
publish_to: 'none'
homepage:

environment:
  sdk: ^3.10.4
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.17.0
  keychain:
    path: ../keychain
  keystore:
    path: ../keystore
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: keystore
      ios:
        default_package: keychain
      macos:
        default_package: keychain
